//! GENERATED by assets/gen_logo.py — edit the definitions there, never this file.
//! The mark's 16x16 snapped raster; None is transparent.
#![cfg_attr(rustfmt, rustfmt::skip)]
pub const WIDTH: usize = 16;
pub const HEIGHT: usize = 16;
pub const GRID: [[Option<(u8, u8, u8)>; WIDTH]; HEIGHT] = [
    [None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    [None, None, None, Some((217, 95, 76)), None, None, None, None, Some((120, 129, 143)), Some((120, 129, 143)), None, Some((120, 129, 143)), Some((120, 129, 143)), None, Some((120, 129, 143)), Some((120, 129, 143))],
    [Some((217, 130, 43)), Some((217, 130, 43)), None, None, None, Some((42, 157, 143)), None, None, Some((120, 129, 143)), Some((120, 129, 143)), None, Some((120, 129, 143)), Some((120, 129, 143)), None, Some((120, 129, 143)), Some((120, 129, 143))],
    [None, None, None, None, Some((120, 129, 143)), None, None, None, None, None, None, None, None, None, None, None],
    [None, None, None, None, None, None, None, None, Some((217, 130, 43)), Some((217, 130, 43)), None, Some((42, 157, 143)), Some((42, 157, 143)), None, Some((217, 95, 76)), Some((217, 95, 76))],
    [None, Some((42, 157, 143)), None, None, None, Some((217, 130, 43)), None, None, Some((217, 130, 43)), Some((217, 130, 43)), None, Some((42, 157, 143)), Some((42, 157, 143)), None, Some((217, 95, 76)), Some((217, 95, 76))],
    [None, Some((42, 157, 143)), None, Some((217, 130, 43)), Some((217, 130, 43)), None, None, None, None, None, None, None, None, None, None, None],
    [Some((217, 95, 76)), None, None, None, None, None, None, None, Some((217, 130, 43)), Some((217, 130, 43)), None, Some((42, 157, 143)), Some((42, 157, 143)), None, Some((217, 95, 76)), Some((217, 95, 76))],
    [None, None, None, None, Some((42, 157, 143)), None, None, None, Some((217, 130, 43)), Some((217, 130, 43)), None, Some((42, 157, 143)), Some((42, 157, 143)), None, Some((217, 95, 76)), Some((217, 95, 76))],
    [None, None, None, None, Some((42, 157, 143)), None, None, None, None, None, None, None, None, None, None, None],
    [None, Some((217, 95, 76)), Some((217, 95, 76)), None, None, None, None, None, Some((217, 130, 43)), Some((217, 130, 43)), None, Some((42, 157, 143)), Some((42, 157, 143)), None, Some((217, 95, 76)), Some((217, 95, 76))],
    [None, None, None, Some((42, 157, 143)), None, None, Some((217, 95, 76)), None, Some((217, 130, 43)), Some((217, 130, 43)), None, Some((42, 157, 143)), Some((42, 157, 143)), None, Some((217, 95, 76)), Some((217, 95, 76))],
    [Some((217, 130, 43)), None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    [None, None, None, None, None, Some((217, 130, 43)), None, None, Some((217, 130, 43)), Some((217, 130, 43)), None, Some((42, 157, 143)), Some((42, 157, 143)), None, Some((217, 95, 76)), Some((217, 95, 76))],
    [None, None, Some((120, 129, 143)), Some((120, 129, 143)), None, None, None, None, Some((217, 130, 43)), Some((217, 130, 43)), None, Some((42, 157, 143)), Some((42, 157, 143)), None, Some((217, 95, 76)), Some((217, 95, 76))],
    [None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
];
